# MySQL connection. If 'Use MySQL' is set to false BookStats will use flat file.
MySQL:
    Use MySQL: false
    IP Address: localhost
    Port: 3306
    User: notroot
    Pass: notmypassword
    Database: BookStats
    Table: BookStats

# How often BookStats will save data. In minutes.
Save Interval: 2

# Book customization
Book:
- "&b&l{Player}'s Stats!"
- " "
- "&1Balance: &4{Balance}"
- " "
- "&1Kills: &4{Kills}"
- " "
- "&1Deaths: &4{Deaths}"
- " "
- "&1Kill Streak: &4{Killstreak}"
- " "
- "&1Mob Kills: &4{Mobkills}"
- " "
- "&1Block Placed: &4{Blocksplaced}"
- "/p"
- "&1Block Broken: &4{Blocksbroken}"

Book Title: "&6{Player}'s Stats"
Book Author: "&aBookStats"

On Join:
    # Give BookStats on join 
    Give Book: false
    # Only give one book
    Give Limit: true
    # Set which slot the book should be put in. If set to 0 it will just add it to the players inventory.
    Slot: 0
    # Prevent dropping books.
    Prevent Drop: false
    # Prevent dragging books or moving book.
    Prevent Drag: false

On Death:
    # Remove BookStat book from there dropped items on death.
    Death Remove: false
    # Give BookStats on death 
    Give Book: false
    # Set which slot the book should be put in. If set to 0 it will just add it to the players inventory.
    Slot: 0
   
# Only will give book if the players inventory does not contain a bookstat book. 
Book Limit: false
Book Limit Message: '&4You can only have one book at a time!'

# Update BookStat books every time it's opened.
Update Book: true